services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
    volumes:
      - db:/var/lib/mysql
    ports:
      - "3307:3306"

volumes:
  db:
